services:
  - type: web
    name: generate-leads-backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm prisma generate && pnpm run build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: FB_CLIENT_ID
        sync: false
      - key: FB_CLIENT_SECRET
        sync: false
      - key: FB_CALLBACK_URL
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: OPENAI_API_KEY
        sync: false

      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false

      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
